# Generated by Django 6.1.1 on 2026-09-29 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_default_workspace'),
        ('pipelines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_video_id', models.TextField()),
                ('status', models.TextField(choices=[('not_delivered', 'Not delivered'), ('queued', 'Queued'), ('uploading', 'Uploading'), ('uploaded', 'Uploaded'), ('failed', 'Failed'), ('removed', 'Removed')], default='not_delivered')),
                ('destination_video_id', models.TextField(blank=True, null=True)),
                ('destination_url', models.TextField(default='')),
                ('destination_title', models.TextField(default='')),
                ('source_title_snapshot', models.TextField(default='')),
                ('provenance_marker', models.TextField(default='')),
                ('match_method', models.TextField(choices=[('ledger', 'Ledger'), ('marker', 'Marker'), ('fingerprint', 'Fingerprint'), ('manual', 'Manual')], default='ledger')),
                ('privacy', models.TextField(default='unlisted')),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(default='')),
                ('last_job_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='deliveries', to='pipelines.destination')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='accounts.workspace')),
            ],
            options={
                'db_table': 'delivery',
            },
        ),
        migrations.CreateModel(
            name='DeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_no', models.IntegerField()),
                ('status', models.TextField(choices=[('uploading', 'Uploading'), ('uploaded', 'Uploaded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')])),
                ('origin', models.TextField(choices=[('system', 'System'), ('retry', 'Retry'), ('manual', 'Manual')], default='system')),
                ('destination_video_id', models.TextField(blank=True, null=True)),
                ('destination_url', models.TextField(default='')),
                ('privacy', models.TextField(default='unlisted')),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('error_code', models.TextField(default='')),
                ('error_message', models.TextField(default='')),
                ('bytes_sent', models.BigIntegerField(default=0)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='delivery.delivery')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='accounts.workspace')),
            ],
            options={
                'db_table': 'delivery_attempt',
            },
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['destination', 'status'], name='delivery_destination_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['workspace', 'source_video_id'], name='delivery_video_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['destination', '-uploaded_at'], name='delivery_retention_idx'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.UniqueConstraint(fields=('workspace', 'source_video_id', 'destination'), name='uq_delivery_pair'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['not_delivered', 'queued', 'uploading', 'uploaded', 'failed', 'removed'])), name='ck_delivery_status'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.CheckConstraint(condition=models.Q(('match_method__in', ['ledger', 'marker', 'fingerprint', 'manual'])), name='ck_delivery_match_method'),
        ),
        migrations.AddIndex(
            model_name='deliveryattempt',
            index=models.Index(fields=['delivery', '-attempt_no'], name='delivery_attempt_recent_idx'),
        ),
        migrations.AddConstraint(
            model_name='deliveryattempt',
            constraint=models.UniqueConstraint(fields=('delivery', 'attempt_no'), name='uq_delivery_attempt_no'),
        ),
        migrations.AddConstraint(
            model_name='deliveryattempt',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_no__gte', 1)), name='ck_attempt_no'),
        ),
        migrations.AddConstraint(
            model_name='deliveryattempt',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['uploading', 'uploaded', 'failed', 'cancelled'])), name='ck_attempt_status'),
        ),
        migrations.AddConstraint(
            model_name='deliveryattempt',
            constraint=models.CheckConstraint(condition=models.Q(('origin__in', ['system', 'retry', 'manual'])), name='ck_attempt_origin'),
        ),
    ]
