# Generated by Django 6.1.1 on 2026-09-29 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_default_workspace'),
        ('jobs', '0001_initial'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageRoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('path', models.TextField()),
                ('role', models.TextField(choices=[('hot', 'Hot'), ('cold', 'Cold')], default='hot')),
                ('priority', models.IntegerField(default=100)),
                ('min_free_bytes', models.BigIntegerField(default=10737418240)),
                ('is_mounted', models.BooleanField(default=True)),
                ('free_bytes', models.BigIntegerField(blank=True, null=True)),
                ('total_bytes', models.BigIntegerField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_roots', to='accounts.workspace')),
            ],
            options={
                'db_table': 'storage_root',
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_video_id', models.TextField()),
                ('materialization_no', models.IntegerField(default=1)),
                ('path', models.TextField()),
                ('filename', models.TextField(default='')),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('sha256', models.TextField(default='')),
                ('duration_sec', models.IntegerField(blank=True, null=True)),
                ('state', models.TextField(choices=[('expected', 'Expected'), ('downloading', 'Downloading'), ('on_disk', 'On disk'), ('archive_offline', 'Archived (offline)'), ('deleted', 'Deleted'), ('failed', 'Failed')], default='expected')),
                ('pinned_until', models.DateTimeField(blank=True, null=True)),
                ('pinned_reason', models.TextField(default='')),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('delete_after', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('delete_reason', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_assets', to='jobs.job')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_assets', to='sources.source')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='accounts.workspace')),
                ('storage_root', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_assets', to='media.storageroot')),
            ],
            options={
                'db_table': 'media_asset',
            },
        ),
        migrations.CreateModel(
            name='MediaEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_video_id', models.TextField()),
                ('event', models.TextField(choices=[('created', 'Created'), ('verified', 'Verified'), ('pinned', 'Pinned'), ('unpinned', 'Unpinned'), ('delete_scheduled', 'Delete scheduled'), ('delete_skipped', 'Delete skipped'), ('deleted', 'Deleted'), ('rehydrated', 'Rehydrated'), ('archive_offline', 'Archived offline')])),
                ('reason', models.TextField(default='')),
                ('bytes', models.BigIntegerField(default=0)),
                ('actor', models.TextField(default='system')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='media.mediaasset')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_events', to='accounts.workspace')),
            ],
            options={
                'db_table': 'media_event',
                'indexes': [models.Index(fields=['workspace', '-created_at'], name='media_event_recent_idx'), models.Index(fields=['workspace', 'source_video_id'], name='media_event_video_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('event__in', ['created', 'verified', 'pinned', 'unpinned', 'delete_scheduled', 'delete_skipped', 'deleted', 'rehydrated', 'archive_offline'])), name='ck_media_event_kind')],
            },
        ),
        migrations.AddIndex(
            model_name='storageroot',
            index=models.Index(fields=['workspace', 'is_active', 'role', 'priority'], name='storage_root_pick_idx'),
        ),
        migrations.AddConstraint(
            model_name='storageroot',
            constraint=models.UniqueConstraint(fields=('workspace', 'path'), name='uq_storage_root_path'),
        ),
        migrations.AddConstraint(
            model_name='storageroot',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['hot', 'cold'])), name='ck_storage_root_role'),
        ),
        migrations.AddConstraint(
            model_name='storageroot',
            constraint=models.CheckConstraint(condition=models.Q(('min_free_bytes__gte', 0)), name='ck_storage_root_min_free'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['workspace', 'state'], name='media_asset_state_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['workspace', 'source_video_id'], name='media_asset_video_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(condition=models.Q(('state', 'on_disk')), fields=['delete_after'], name='media_asset_due_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['storage_root_id', 'state'], name='media_asset_root_idx'),
        ),
        migrations.AddConstraint(
            model_name='mediaasset',
            constraint=models.UniqueConstraint(fields=('workspace', 'source_video_id', 'materialization_no'), name='uq_media_asset_copy'),
        ),
        migrations.AddConstraint(
            model_name='mediaasset',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['expected', 'downloading', 'on_disk', 'archive_offline', 'deleted', 'failed'])), name='ck_media_asset_state'),
        ),
        migrations.AddConstraint(
            model_name='mediaasset',
            constraint=models.CheckConstraint(condition=models.Q(('materialization_no__gte', 1)), name='ck_media_asset_copy_no'),
        ),
    ]
