# Generated by Django 6.1.1 on 2026-09-28 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_default_workspace'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('client_id', models.TextField()),
                ('client_secret_enc', models.BinaryField(default=b'')),
                ('daily_upload_cap', models.IntegerField(default=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_clients', to='accounts.workspace')),
            ],
            options={
                'db_table': 'google_client',
            },
        ),
        migrations.CreateModel(
            name='AuthorizedChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.TextField()),
                ('title', models.TextField(default='')),
                ('access_token_enc', models.BinaryField(blank=True, default=None, null=True)),
                ('refresh_token_enc', models.BinaryField(blank=True, default=None, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('token_state', models.TextField(choices=[('missing', 'Missing'), ('valid', 'Valid'), ('expiring', 'Expiring'), ('invalid', 'Invalid'), ('revoked', 'Revoked')], default='missing')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_channels', to='accounts.workspace')),
                ('google_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channels', to='credentials.googleclient')),
            ],
            options={
                'db_table': 'authorized_channel',
            },
        ),
        migrations.AddIndex(
            model_name='googleclient',
            index=models.Index(fields=['workspace', 'is_active'], name='google_client_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='googleclient',
            constraint=models.UniqueConstraint(fields=('workspace', 'client_id'), name='uq_google_client_client_id'),
        ),
        migrations.AddConstraint(
            model_name='googleclient',
            constraint=models.UniqueConstraint(fields=('workspace', 'label'), name='uq_google_client_label'),
        ),
        migrations.AddConstraint(
            model_name='googleclient',
            constraint=models.CheckConstraint(condition=models.Q(('daily_upload_cap__gt', 0)), name='ck_google_client_cap'),
        ),
        migrations.AddIndex(
            model_name='authorizedchannel',
            index=models.Index(fields=['workspace', 'token_state'], name='authorized_channel_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='authorizedchannel',
            constraint=models.UniqueConstraint(fields=('workspace', 'channel_id'), name='uq_channel_workspace_channel'),
        ),
        migrations.AddConstraint(
            model_name='authorizedchannel',
            constraint=models.CheckConstraint(condition=models.Q(('token_state__in', ['missing', 'valid', 'expiring', 'invalid', 'revoked'])), name='ck_channel_token_state'),
        ),
    ]
