# Generated by Django 6.1.1 on 2026-09-29 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_default_workspace'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.TextField(default='system')),
                ('entity', models.TextField()),
                ('entity_id', models.TextField(default='')),
                ('action', models.TextField()),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='accounts.workspace')),
            ],
            options={
                'db_table': 'audit_event',
                'indexes': [models.Index(fields=['-created_at'], name='audit_event_recent_idx'), models.Index(fields=['entity', 'entity_id'], name='audit_event_entity_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkerHeartbeat',
            fields=[
                ('worker_id', models.TextField(primary_key=True, serialize=False)),
                ('kind', models.TextField(default='')),
                ('status', models.TextField(choices=[('idle', 'Idle'), ('busy', 'Busy'), ('error', 'Error'), ('stopped', 'Stopped')], default='idle')),
                ('detail', models.TextField(default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_beat_at', models.DateTimeField(auto_now=True)),
                ('host', models.TextField(default='')),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('current_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_heartbeats', to='jobs.job')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_heartbeats', to='accounts.workspace')),
            ],
            options={
                'db_table': 'worker_heartbeat',
                'indexes': [models.Index(fields=['last_beat_at'], name='worker_heartbeat_stale_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['idle', 'busy', 'error', 'stopped'])), name='ck_worker_heartbeat_status')],
            },
        ),
    ]
