# Generated by Django 6.1.1 on 2026-09-28 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_default_workspace'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.TextField(choices=[('channel', 'Channel'), ('playlist', 'Playlist')])),
                ('external_id', models.TextField()),
                ('url', models.TextField()),
                ('name', models.TextField(default='')),
                ('is_active', models.BooleanField(default=True)),
                ('scan_status', models.TextField(choices=[('never', 'Never'), ('scanning', 'Scanning'), ('ok', 'Ok'), ('partial', 'Partial'), ('error', 'Error')], default='never')),
                ('last_scan_at', models.DateTimeField(blank=True, null=True)),
                ('last_scan_error', models.TextField(default='')),
                ('video_count', models.IntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='accounts.workspace')),
            ],
            options={
                'db_table': 'source',
            },
        ),
        migrations.CreateModel(
            name='CatalogVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.TextField()),
                ('title', models.TextField(default='')),
                ('duration_sec', models.IntegerField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('thumbnail_url', models.TextField(default='')),
                ('live_status', models.TextField(default='unknown')),
                ('availability', models.TextField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('private', 'Private'), ('unknown', 'Unknown')], default='unknown')),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('view_count', models.BigIntegerField(blank=True, null=True)),
                ('like_count', models.BigIntegerField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('hydrated_at', models.DateTimeField(blank=True, null=True)),
                ('starred', models.BooleanField(default=False)),
                ('ignored', models.BooleanField(default=False)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_videos', to='accounts.workspace')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='sources.source')),
            ],
            options={
                'db_table': 'catalog_video',
            },
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['workspace', 'is_active', 'last_scan_at'], name='source_scan_idx'),
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.UniqueConstraint(fields=('workspace', 'external_id'), name='uq_source_workspace_external'),
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['channel', 'playlist'])), name='ck_source_kind'),
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.CheckConstraint(condition=models.Q(('scan_status__in', ['never', 'scanning', 'ok', 'partial', 'error'])), name='ck_source_scan_status'),
        ),
        migrations.AddIndex(
            model_name='catalogvideo',
            index=models.Index(fields=['source', '-published_at'], name='catalog_video_source_date_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogvideo',
            index=models.Index(fields=['workspace', 'video_id'], name='catalog_video_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogvideo',
            index=models.Index(fields=['source', 'hydrated_at'], name='catalog_video_hydrate_idx'),
        ),
        migrations.AddConstraint(
            model_name='catalogvideo',
            constraint=models.UniqueConstraint(fields=('source', 'video_id'), name='uq_catalog_video_source_video'),
        ),
        migrations.AddConstraint(
            model_name='catalogvideo',
            constraint=models.CheckConstraint(condition=models.Q(('availability__in', ['available', 'unavailable', 'private', 'unknown'])), name='ck_catalog_video_availability'),
        ),
    ]
