# Generated by Django 6.1.1 on 2026-09-29 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_default_workspace'),
        ('pipelines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_video_id', models.TextField()),
                ('title', models.TextField(default='')),
                ('description_excerpt', models.TextField(default='')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('privacy', models.TextField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('private', 'Private'), ('unknown', 'Unknown')], default='unknown')),
                ('duration_sec', models.IntegerField(blank=True, null=True)),
                ('provenance_marker', models.TextField(blank=True, null=True)),
                ('matched_delivery_id', models.BigIntegerField(blank=True, null=True)),
                ('match_method', models.TextField(choices=[('none', 'None'), ('marker', 'Marker'), ('ledger', 'Ledger'), ('fingerprint', 'Fingerprint')], default='none')),
                ('is_present', models.BooleanField(default=True)),
                ('first_observed_at', models.DateTimeField(auto_now_add=True)),
                ('last_observed_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='pipelines.destination')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_inventory', to='accounts.workspace')),
            ],
            options={
                'db_table': 'destination_inventory',
                'indexes': [models.Index(condition=models.Q(('matched_delivery_id__isnull', True)), fields=['destination', 'matched_delivery_id'], name='inv_unclaimed_idx'), models.Index(fields=['destination', 'title'], name='inv_title_idx')],
                'constraints': [models.UniqueConstraint(fields=('destination', 'destination_video_id'), name='uq_destination_inventory_video'), models.CheckConstraint(condition=models.Q(('privacy__in', ['public', 'unlisted', 'private', 'unknown'])), name='ck_destination_inventory_privacy'), models.CheckConstraint(condition=models.Q(('match_method__in', ['none', 'marker', 'ledger', 'fingerprint'])), name='ck_destination_inventory_match_method')],
            },
        ),
        migrations.CreateModel(
            name='QuotaUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota_date', models.DateField()),
                ('uploads_used', models.IntegerField(default=0)),
                ('units_used', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota_usage', to='pipelines.destination')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota_usage', to='accounts.workspace')),
            ],
            options={
                'db_table': 'quota_usage',
                'indexes': [models.Index(fields=['destination', '-quota_date'], name='quota_usage_recent_idx')],
                'constraints': [models.UniqueConstraint(fields=('destination', 'quota_date'), name='uq_quota_usage_day'), models.CheckConstraint(condition=models.Q(('uploads_used__gte', 0)), name='ck_quota_usage_uploads'), models.CheckConstraint(condition=models.Q(('units_used__gte', 0)), name='ck_quota_usage_units')],
            },
        ),
    ]
