"""Turn `matched_delivery_id` into the foreign key docs/03 §8 always declared.

U09 shipped this column as a plain `bigint` because `delivery` did not exist
yet, and recorded the deferral in `youtube/CONTRACT.md` §5.1. U10 creates
`delivery`, so the constraint can finally exist.

The column name is unchanged — Django's foreign key attname is also
`matched_delivery_id` — so every query and the partial index on it are
unaffected; only the type and the referential integrity change.

**Data caveat:** Django expresses a `bigint` → `ForeignKey` change as a remove
plus an add, which drops the values in a populated table. That is safe here
because `destination_inventory` has never held a match: U09 wrote the column
but nothing could populate it, since only `delivery` sets it. On a
pre-production install the equivalent migration should be a hand-written
`ALTER TABLE ... ADD CONSTRAINT`, which preserves the values.
"""

# Generated by Django 6.1.1 on 2026-09-29 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
        ('youtube', '0001_initial'),
    ]

    operations = [
        # The index goes first: it is a *partial* index on `matched_delivery_id`,
        # and SQLite refuses to drop a column an index still refers to ("error in
        # index inv_unclaimed_idx after drop column"). PostgreSQL would cascade
        # the index away silently, so this ordering only bites on the test
        # harness — which is precisely what the harness is for.
        migrations.RemoveIndex(
            model_name="destinationinventory",
            name="inv_unclaimed_idx",
        ),
        migrations.RemoveField(
            model_name="destinationinventory",
            name="matched_delivery_id",
        ),
        migrations.AddField(
            model_name="destinationinventory",
            name="matched_delivery",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="inventory_rows", to="delivery.delivery"),
        ),
        migrations.AddIndex(
            model_name="destinationinventory",
            index=models.Index(
                condition=models.Q(("matched_delivery_id__isnull", True)),
                fields=["destination", "matched_delivery_id"],
                name="inv_unclaimed_idx",
            ),
        ),
    ]
