# Generated by Django 6.1.1 on 2026-09-28 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_default_workspace'),
        ('credentials', '0001_initial'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('platform', models.TextField(default='youtube')),
                ('default_privacy', models.TextField(choices=[('private', 'Private'), ('unlisted', 'Unlisted'), ('public', 'Public')], default='unlisted')),
                ('daily_max', models.IntegerField(default=6)),
                ('enabled', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_error', models.TextField(default='')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorized_channel', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='destinations', to='credentials.authorizedchannel')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='accounts.workspace')),
            ],
            options={
                'db_table': 'destination',
            },
        ),
        migrations.CreateModel(
            name='DownloadProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('max_height', models.IntegerField(default=0)),
                ('container', models.TextField(default='mp4')),
                ('video_codec', models.TextField(default='any')),
                ('audio_codec', models.TextField(default='any')),
                ('write_subs', models.BooleanField(default=True)),
                ('sub_langs', models.JSONField(blank=True, default=list)),
                ('write_thumbnail', models.BooleanField(default=True)),
                ('write_info_json', models.BooleanField(default=True)),
                ('skip_shorts', models.BooleanField(default=False)),
                ('shorts_max_seconds', models.IntegerField(default=60)),
                ('skip_live', models.BooleanField(default=True)),
                ('extra_ytdlp_opts', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_profiles', to='accounts.workspace')),
            ],
            options={
                'db_table': 'download_profile',
            },
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(default='')),
                ('status', models.TextField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused')], default='draft')),
                ('priority', models.IntegerField(default=100)),
                ('default_privacy', models.TextField(choices=[('private', 'Private'), ('unlisted', 'Unlisted'), ('public', 'Public')], default='unlisted')),
                ('provenance_marker', models.BooleanField(default=True)),
                ('retention_mode', models.TextField(choices=[('keep', 'Keep'), ('immediate', 'Immediate'), ('after_n_jobs', 'After N jobs'), ('after_hours', 'After N hours')], default='keep')),
                ('retention_n', models.IntegerField(default=2)),
                ('retention_hours', models.IntegerField(default=24)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('download_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipelines', to='pipelines.downloadprofile')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='accounts.workspace')),
            ],
            options={
                'db_table': 'pipeline',
            },
        ),
        migrations.CreateModel(
            name='PipelineDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=100)),
                ('privacy_override', models.TextField(blank=True, choices=[('private', 'Private'), ('unlisted', 'Unlisted'), ('public', 'Public')], null=True)),
                ('retention_mode_override', models.TextField(blank=True, choices=[('keep', 'Keep'), ('immediate', 'Immediate'), ('after_n_jobs', 'After N jobs'), ('after_hours', 'After N hours')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_destinations', to='pipelines.destination')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_destinations', to='pipelines.pipeline')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_destinations', to='accounts.workspace')),
            ],
            options={
                'db_table': 'pipeline_destination',
            },
        ),
        migrations.CreateModel(
            name='PipelineSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.TextField(choices=[('monitor', 'Monitor'), ('backfill', 'Backfill')], default='monitor')),
                ('priority', models.IntegerField(default=100)),
                ('daily_cap', models.IntegerField(blank=True, null=True)),
                ('backfill_state', models.TextField(choices=[('not_started', 'Not started'), ('running', 'Running'), ('paused', 'Paused'), ('complete', 'Complete'), ('stopped', 'Stopped')], default='not_started')),
                ('backfill_cursor_published_at', models.DateTimeField(blank=True, null=True)),
                ('backfill_done_count', models.IntegerField(default=0)),
                ('backfill_total_count', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_sources', to='pipelines.pipeline')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_sources', to='sources.source')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_sources', to='accounts.workspace')),
            ],
            options={
                'db_table': 'pipeline_source',
            },
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['workspace', 'enabled'], name='destination_enabled_idx'),
        ),
        migrations.AddConstraint(
            model_name='destination',
            constraint=models.UniqueConstraint(fields=('workspace', 'label'), name='uq_destination_workspace_label'),
        ),
        migrations.AddConstraint(
            model_name='destination',
            constraint=models.CheckConstraint(condition=models.Q(('platform', 'youtube')), name='ck_destination_platform'),
        ),
        migrations.AddConstraint(
            model_name='destination',
            constraint=models.CheckConstraint(condition=models.Q(('default_privacy__in', ['private', 'unlisted', 'public'])), name='ck_destination_default_privacy'),
        ),
        migrations.AddConstraint(
            model_name='destination',
            constraint=models.CheckConstraint(condition=models.Q(('daily_max__gt', 0)), name='ck_destination_daily_max'),
        ),
        migrations.AddConstraint(
            model_name='downloadprofile',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='uq_download_profile_workspace_name'),
        ),
        migrations.AddConstraint(
            model_name='downloadprofile',
            constraint=models.CheckConstraint(condition=models.Q(('max_height__gte', 0)), name='ck_download_profile_height'),
        ),
        migrations.AddIndex(
            model_name='pipeline',
            index=models.Index(fields=['workspace', 'status', 'priority'], name='pipeline_run_idx'),
        ),
        migrations.AddConstraint(
            model_name='pipeline',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='uq_pipeline_workspace_name'),
        ),
        migrations.AddConstraint(
            model_name='pipeline',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'active', 'paused'])), name='ck_pipeline_status'),
        ),
        migrations.AddConstraint(
            model_name='pipeline',
            constraint=models.CheckConstraint(condition=models.Q(('default_privacy__in', ['private', 'unlisted', 'public'])), name='ck_pipeline_default_privacy'),
        ),
        migrations.AddConstraint(
            model_name='pipeline',
            constraint=models.CheckConstraint(condition=models.Q(('retention_mode__in', ['keep', 'immediate', 'after_n_jobs', 'after_hours'])), name='ck_pipeline_retention_mode'),
        ),
        migrations.AddConstraint(
            model_name='pipeline',
            constraint=models.CheckConstraint(condition=models.Q(('retention_n__gte', 1)), name='ck_pipeline_retention_n'),
        ),
        migrations.AddConstraint(
            model_name='pipeline',
            constraint=models.CheckConstraint(condition=models.Q(('retention_hours__gte', 1)), name='ck_pipeline_retention_hours'),
        ),
        migrations.AddIndex(
            model_name='pipelinedestination',
            index=models.Index(fields=['pipeline', 'enabled'], name='pipeline_destination_idx'),
        ),
        migrations.AddConstraint(
            model_name='pipelinedestination',
            constraint=models.UniqueConstraint(fields=('pipeline', 'destination'), name='uq_pipeline_destination_pair'),
        ),
        migrations.AddConstraint(
            model_name='pipelinedestination',
            constraint=models.CheckConstraint(condition=models.Q(('privacy_override__in', ['private', 'unlisted', 'public']), ('privacy_override__isnull', True), _connector='OR'), name='ck_pipeline_destination_privacy'),
        ),
        migrations.AddConstraint(
            model_name='pipelinedestination',
            constraint=models.CheckConstraint(condition=models.Q(('retention_mode_override__in', ['keep', 'immediate', 'after_n_jobs', 'after_hours']), ('retention_mode_override__isnull', True), _connector='OR'), name='ck_pipeline_destination_retention'),
        ),
        migrations.AddIndex(
            model_name='pipelinesource',
            index=models.Index(fields=['pipeline', 'backfill_state'], name='pipeline_source_backfill_idx'),
        ),
        migrations.AddConstraint(
            model_name='pipelinesource',
            constraint=models.UniqueConstraint(fields=('pipeline', 'source'), name='uq_pipeline_source_pair'),
        ),
        migrations.AddConstraint(
            model_name='pipelinesource',
            constraint=models.CheckConstraint(condition=models.Q(('mode__in', ['monitor', 'backfill'])), name='ck_pipeline_source_mode'),
        ),
        migrations.AddConstraint(
            model_name='pipelinesource',
            constraint=models.CheckConstraint(condition=models.Q(('backfill_state__in', ['not_started', 'running', 'paused', 'complete', 'stopped'])), name='ck_pipeline_source_backfill_state'),
        ),
        migrations.AddConstraint(
            model_name='pipelinesource',
            constraint=models.CheckConstraint(condition=models.Q(('daily_cap__isnull', True), ('daily_cap__gt', 0), _connector='OR'), name='ck_pipeline_source_daily_cap'),
        ),
    ]
