# Generated by Django 6.1.1 on 2026-09-28 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_default_workspace'),
        ('pipelines', '0001_initial'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_video_id', models.TextField()),
                ('intent', models.TextField(choices=[('upload', 'Upload'), ('rehydrate', 'Rehydrate'), ('inspect', 'Inspect')], default='upload')),
                ('status', models.TextField(choices=[('queued', 'Queued'), ('claimed', 'Claimed'), ('downloading', 'Downloading'), ('downloaded', 'Downloaded'), ('uploading', 'Uploading'), ('uploaded', 'Uploaded'), ('failed_transient', 'Failed (transient)'), ('failed_permanent', 'Failed (permanent)'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], default='queued')),
                ('priority', models.IntegerField(default=100)),
                ('attempt_count', models.IntegerField(default=0)),
                ('claimed_by', models.TextField(default='')),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('claim_expires_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.TextField(default='')),
                ('error_message', models.TextField(default='')),
                ('skip_reason', models.TextField(default='')),
                ('bytes_downloaded', models.BigIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='pipelines.pipeline')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='sources.source')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.workspace')),
            ],
            options={
                'db_table': 'job',
                'indexes': [models.Index(condition=models.Q(('status', 'queued')), fields=['priority', 'created_at'], name='job_claim_idx'), models.Index(fields=['workspace', 'pipeline', 'status'], name='job_pipeline_idx'), models.Index(fields=['workspace', 'source_video_id'], name='job_video_idx'), models.Index(fields=['status', 'claim_expires_at'], name='job_stale_claim_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['cancelled', 'skipped']), _negated=True), fields=('workspace', 'pipeline', 'source_video_id', 'intent'), name='job_live_unique'), models.CheckConstraint(condition=models.Q(('status__in', ['queued', 'claimed', 'downloading', 'downloaded', 'uploading', 'uploaded', 'failed_transient', 'failed_permanent', 'skipped', 'cancelled'])), name='ck_job_status'), models.CheckConstraint(condition=models.Q(('intent__in', ['upload', 'rehydrate', 'inspect'])), name='ck_job_intent'), models.CheckConstraint(condition=models.Q(('attempt_count__gte', 0)), name='ck_job_attempt_count')],
            },
        ),
    ]
